[[headers]]
  for = "/gallery.html"
  [headers.values]
    Basic-Auth = "manish:manish8090"

[[headers]]
  for = "/gallery/*"
  [headers.values]
    Basic-Auth = "manish:manish8090"

[[headers]]
  for = "/manish-img/*"
  [headers.values]
    Basic-Auth = "manish:manish8090"
